### ISSUE TITLE
Graphical glitch in edit style

### ISSUE THREAD

**Issue by thomaspiller** [fxi/map-x-mgl#138]
Rules overflow to the right in the "edit style" panel.

<img src="https://user-images.githubusercontent.com/19908801/32648855-00860c7a-c5f8-11e7-9bac-d2d9253e559e.png" width="50%">

## Possible solution

Add {overflow: hidden} to the style of _.well-sm_

**Comment by fxi** [comment]
Thanks.

Fixed bootstrap default as:

```css
.jed-container .well {
  padding: 10px 5px 10px 5px;
  border: none;
  box-shadow: none;
  --webkit-box-shadow: none;
  overflow: hidden;
}
```
